## **Library Imports**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

## **Data Loading**

In [2]:
dataset = pd.read_csv("old_cardata.csv")

## **Data Preview**

In [3]:
dataset.head()

,Car_Name,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Selling_Price
0,ritz,2014,5.59,27000,Petrol,Dealer,Manual,0,3.35
1,sx4,2013,9.54,43000,Diesel,Dealer,Manual,0,4.75
2,ciaz,2017,9.85,6900,Petrol,Dealer,Manual,0,7.25
3,wagon r,2011,4.15,5200,Petrol,Dealer,Manual,0,2.85
4,swift,2014,6.87,42450,Diesel,Dealer,Manual,0,4.60

In [4]:
dataset.isnull().sum()

Car_Name         0
Year             0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
Selling_Price    0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Present_Price  301 non-null    float64
 3   Kms_Driven     301 non-null    int64
 4   Fuel_Type      301 non-null    object
 5   Seller_Type    301 non-null    object
 6   Transmission   301 non-null    object
 7   Owner          301 non-null    int64
 8   Selling_Price  301 non-null    float64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

## **Categorical Variable Encoding using LabelEncoder**

## **Car_Name**

In [7]:
Car_Name_le = LabelEncoder()
dataset["Car_Name"] = Car_Name_le.fit_transform(dataset["Car_Name"])

## **Fuel_Type**

In [8]:
dataset["Fuel_Type"].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [9]:
Fule_Type_le = LabelEncoder()
dataset["Fuel_Type"] = Fule_Type_le.fit_transform(dataset["Fuel_Type"])

## **Seller_Type**

In [10]:
dataset["Seller_Type"].unique()

array(['Dealer', 'Individual'], dtype=object)

In [11]:
Seller_Type_le = LabelEncoder()
dataset["Seller_Type"] = Seller_Type_le.fit_transform(dataset["Seller_Type"])

## **Transmission**

In [12]:
dataset["Transmission"].unique()

array(['Manual', 'Automatic'], dtype=object)

In [13]:
Transmission_le = LabelEncoder()
dataset["Transmission"] = Transmission_le.fit_transform(dataset["Transmission"])

## **Dataset After Label Encoding**

In [14]:
dataset.head()

,Car_Name,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Selling_Price
0,90,2014,5.59,27000,2,0,1,0,3.35
1,93,2013,9.54,43000,1,0,1,0,4.75
2,68,2017,9.85,6900,2,0,1,0,7.25
3,96,2011,4.15,5200,2,0,1,0,2.85
4,92,2014,6.87,42450,1,0,1,0,4.60

## **Input & Output Data**

In [15]:
input_data = dataset.iloc[:,:-1]
output_data = dataset["Selling_Price"]

## **Standard Scaling of Input Features**

In [16]:
ss = StandardScaler()
input_data = pd.DataFrame(ss.fit_transform(input_data), columns=input_data.columns)

## **Train-Test Split Configuration**

In [17]:
X_train, X_test, y_train, y_test = train_test_split(input_data, output_data,test_size=0.2, random_state=42)

## **Random Forest Regressor Model Implementation**

In [18]:
rf = RandomForestRegressor(n_estimators=100)
rf.fit(X_train, y_train)
rf.score(X_train, y_train)*100, rf.score(X_test, y_test)*100

(98.4265314085461, 96.7848892933021)

## **Error Analysis of Random Forest Regression Model(MSE & MAE)**

In [19]:
mean_squared_error(y_test, rf.predict(X_test)), mean_absolute_error(y_test, rf.predict(X_test))

(0.7406195442622948, 0.5714852459016393)

## **Single-Instance Prediction Output**

In [22]:
rf.predict([[-1.275759,0.821718,-0.817924,-0.333500,0.500183,1.356327,-2.554408,-0.17450]])

C:\Users\DELL\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([0.4381])

## **Car Price Prediction - New Data Preparation & Encoding**

In [24]:
new_data = pd.DataFrame([["ritz",2014,5.59,27000,"Petrol","Dealer","Manual",0]],columns=X_train.columns)

In [25]:
new_data

,Car_Name,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,5.59,27000,Petrol,Dealer,Manual,0

In [26]:
new_data["Car_Name"] = Car_Name_le.transform(new_data["Car_Name"])

In [27]:
new_data["Fuel_Type"] = Fule_Type_le.transform(new_data["Fuel_Type"])

In [28]:
new_data["Seller_Type"] = Seller_Type_le.transform(new_data["Seller_Type"])

In [29]:
new_data["Transmission"] = Transmission_le.transform(new_data["Transmission"])

In [30]:
new_data = pd.DataFrame(ss.transform(new_data), columns=new_data.columns)

In [31]:
new_data

,Car_Name,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,1.074323,0.128897,-0.236215,-0.256224,0.500183,-0.737285,0.39148,-0.174501

## **Random Forest Prediction on New Data**

In [32]:
rf.predict(new_data)

array([3.859])